# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e9581a86681fe74241318993751692ca8db04574ecaee7fe02a87fe7f142e860ffb12bfb9f1eeb283a816a002322d0ea319f52fd4dd592bb3f46fec8b1ecd60

test:
  secret_key_base: c0eec0b83292c492dcd32a494fa86b824fb090c2b4e756459f8e97486e3710f785dd853e8185b14391c9024046ae833e9c26dbb53da94e32b93b17754e9180fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
